#!/usr/bin/env zsh
# vim:set sw=2 sts=2 ts=2 et:

function linkToPath() {
  #function_body
  local bin_path="${1}"
  local destination="$HOME/.local/bin/"
  if [[ -e "$bin_path"  ]]; then
    ln -sf "${bin_path:A}" "${destination}${bin_path:t}"
  fi
}

echo "Using home: $HOME"

echo "Removing existing python install and virtualenvs..."
rm -rf "$HOME/.virtualenvs/neovim3"
rm -rf "$PYENV_ROOT/versions"
rm -rf "$HOME/.yarn/bin"
rm -rf "$HOME/.config/yarn"
rm -rf "$HOME/.local/share/nvm/versions/*"

# Install python3.7
if ! pyenv versions --bare | sort -n | head | grep -q -c "^3." ; then
  pyenv install-latest 3
fi

# Set pyenv default python version
python_ver="$(pyenv versions --bare | sort -n | head | grep  "^3.")"
# get latest python
python_bin="$PYENV_ROOT/versions/$python_ver/bin/python"

# Check for neovim3 virtualenv
source /usr/share/virtualenvwrapper/virtualenvwrapper.sh
if [[ ! -d $HOME/.virtualenvs/neovim3 ]]; then
  mkvirtualenv -p "${python_bin:A}" neovim3
fi

# Install python modules
workon neovim3
pip3 install -U pip
pip3 install -U \
  setuptools \
  wheel
pip install -U \
  flake8 \
  jedi \
  psutil \
  setproctitle \
  python-language-server \
  yamllint \
  pynvim \
  neovim-remote

# Install node support
source "$HOME/.local/share/nvm/nvm.sh"
nvm install node
npm i -g yarn
yarn global add \
  prettier \
  dockerfile-language-server-nodejs \
  javascript-typescript-langserver \
  neovim

# Setup superseding binaries
binaries=("$HOME/.virtualenvs/neovim3/bin/nvr" \
  "$HOME/.virtualenvs/neovim3/bin/yamllint" \
  "$HOME/.virtualenvs/neovim3/bin/flake8" \
  "$HOME/.virtualenvs/neovim3/bin/pyls" )

mkdir -p "$HOME/.local/bin"
for bin in "${binaries[@]}"; do
  linkToPath "$bin"
done
