#!/bin/bash

fonts_to_install=("SourceCodePro" "Hack" "InconsolataLGC" "FiraCode")
nerdfont_releases="https://github.com/ryanoasis/nerd-fonts/releases.atom"
download_url_prefix="https://github.com/ryanoasis/nerd-fonts/releases/download"

get_release_ver() {
  url="$1"
  curl -sL "$url" | awk '{
    if ($0 ~ "<entry>") { isRelease=1 }
    if (isRelease == 1 && $0 ~ "title" && done != 1) {
      ver=$0;
      gsub("(</|<)title>","",ver);
      gsub("[[:space:]]+","",ver);
      done=1
    }
  }
  END {printf "%s", ver;}'
}

download_font() {
  font_name="$1"
  curl -o "$tmpdir/$font_name.zip" -sSL "$download_url_prefix/$version/$font_name.zip"
}

install_font() {
  font_name="$1"
  zip_file="$tmpdir/$font_name.zip"
  dest="$HOME/.fonts/$font_name"
  mkdir -p "$dest"
  unzip -C "$zip_file" "*Mono.ttf" -d "$dest"
}

version="$(get_release_ver "$nerdfont_releases")"
tmpdir="$(mktemp -d)"

for font_name in ${fonts_to_install[*]}; do
  download_font "$font_name"
  install_font "$font_name"
done

fc-cache -f -r > /dev/null
rm -rf "$tmpdir"
