#!/usr/bin/env zsh
# vim:set ft=zsh sw=2 sts=2 ts=2 et:

curl -fsSL                                                  \
  https://github.com/Schniz/fnm/raw/master/.ci/install.sh | \
  bash -s -- --install-dir                                  \
    $HOME/.local/bin                                        \
    --skip-shell
