#!/bin/bash
#
#
#
# This script is meant to use with i3blocks. It parses the output of the "acpi"
# command (often provided by a package of the same name) to read the status of
# the battery, and eventually its remaining time (to full charge or discharge).
#
# The color will gradually change for a percentage below 85%, and the urgency
# (exit code 33) is set if there is less that 5% remaining.

BAT_NUMBER="${BLOCK_INSTANCE:-0}"

# read the first line of the "acpi" command output
ACPI_OUTPUT="$(acpi -b | grep "Battery $BAT_NUMBER")"


## fail on unexpected output
PLUG_REGEX=": ([[:alpha:]]+), ([[:digit:]]+)%"
BAT_REGEX=": ([[:alpha:]]+), ([[:digit:]]+)%, ([[:digit:]]+:[[:digit:]]+)"
if [[ $ACPI_OUTPUT =~ $BAT_REGEX || $ACPI_OUTPUT =~ $PLUG_REGEX ]]
then
	bat_status="${BASH_REMATCH[1]}"
	bat_percent="${BASH_REMATCH[2]}"
	bat_time="${BASH_REMATCH[3]}"
	if [[ "$bat_status" == "Discharging" ]]
	then
		full_text="${bat_percent}% (${bat_time}h)";
	elif [[ $status == "Charging" ]]
	then
		full_text="${bat_percent}%"
	else
		full_text="${bat_percent}%"
	fi
else
	exit 0
fi
short_text=$full_text
echo "$full_text "
echo "$short_text "

# consider color and urgent flag only on discharge
if [[ $status == "Discharging" ||  $status == "Charging" ]]
then
	if [[ $bat_percent -lt 8 ]]
	then
		echo "#FF0000"
		exit 33
	elif [[ $bat_percent -lt 25 ]]
	then
		echo "#FF0000"
	elif [[ $bat_percent -lt 50 ]]
	then
		echo "#FFAE00"
	elif [[ $bat_percent -lt 75 ]]
	then
		echo "#FFF600"
	else
		echo "#FFFFFF"
	fi
else
	echo "#FFFFFF"
fi
