#!/bin/bash

DIR="${BLOCK_INSTANCE:-$HOME}"
ALERT_LOW="${1:-10}" # color will turn red under this value (default: 10%)


btrfs_fi=$(df -T "$DIR" | awk 'END {print $2}')

if [[ $btrfs_fi == "btrfs" ]]
then
	sudo /bin/btrfs filesystem show $DIR | awk -v alert_low=$ALERT_LOW '
	{
		if ($1 == "devid") {
			size=$4;
			used=$6;
			nsize=substr(size, 0, length(size)-3);
			nused=substr(used, 0, length(used)-3);
			units=substr(used, length(used)-2, 1);
			nfree=nsize-nused;
			printf "%s%s\n",nfree,units;
			printf "%s%s\n",nfree,units;

			# no need to continue parsing
			exit 0
		}
	}

	END {
			gsub(/%$/,"",used)
			if (100 - used < alert_low) {
				# color
				print "#FF0000"
		}
	}
	'
else
	df -h -P -l "$DIR" | awk -v alert_low=$ALERT_LOW '
	/\/.*/ {
		# full text
		print $4

		# short text
		print $4

		use=$5

		# no need to continue parsing
		exit 0
	}

	END {
			gsub(/%$/,"",use)
			if (100 - use < alert_low) {
				# color
				print "#FF0000"
			}
	}
	'
fi
