#!/bin/bash
# Displays the default device, volume, and mute status for i3blocks

# shellcheck disable=SC2016
AWK_PA_FILTER='
BEGIN { FS=": | = "; start=0; pa_alsa_name="undefined"; pa_alsa_desc="undefined" }

/\* index/{ start=1 }
{
  if (start == 1)
  {
    if ($0 ~ /index:/)
    {
      pa_index=$2
    }
    if ( $0 ~ /name:/ )
    {
      split($2,pa_names,".")
      pa_name=pa_names[length(pa_names)]
      gsub(/>/,"",pa_name)
    }
    if ( $0 ~ /volume: front-left/ )
    {
      match($3, "([0-9]+)%.*", matches)
      if (length(matches) != 0)
      {
        pa_vol=matches[1]
      }
      else
      {
        pa_vol="0"
      }
    }
    if ( $0 ~ /muted:/ )
    {
      pa_mute=$2
    }
    if ( $0 ~ /alsa.name/ )
    {
      pa_alsa_name = $2
      gsub(/\"/,"",pa_alsa_name)
    }
    if ( $0 ~ /device.description/ )
    {
      pa_dev_desc = $2
      gsub(/\"/,"",pa_dev_desc)
    }
  }
}

END { print pa_index; print pa_name; print pa_vol; print pa_mute; print pa_alsa_name; print pa_dev_desc }
'

AUDIO_HIGH_SYMBOL=' '

AUDIO_MED_THRESH=50
AUDIO_MED_SYMBOL=' '

AUDIO_LOW_THRESH=0
AUDIO_LOW_SYMBOL=' '

AUDIO_MUTED_SYMBOL=' '

AUDIO_INTERVAL=5

DEFAULT_COLOR="#669900"
MUTED_COLOR="#FF0000"

LABEL_ONLY=0
LONG_FORMAT=0
SHORT_FORMAT=2
USE_PERCENT=1
USE_ALSA_NAME=0
USE_DESCRIPTION=0

while getopts F:lf:padH:M:L:X:T:t:C:c:i:h opt; do
  case "$opt" in
      F) LONG_FORMAT="$OPTARG" ;;
      f) SHORT_FORMAT="$OPTARG" ;;
      p) USE_PERCENT=0 ;;
      a) USE_ALSA_NAME=1 ;;
      d) USE_DESCRIPTION=1 ;;
      H) AUDIO_HIGH_SYMBOL="$OPTARG" ;;
      M) AUDIO_MED_SYMBOL="$OPTARG" ;;
      l) LABEL_ONLY=1 ;;
      L) AUDIO_LOW_SYMBOL="$OPTARG" ;;
      X) AUDIO_MUTED_SYMBOL="$OPTARG" ;;
      T) AUDIO_MED_THRESH="$OPTARG" ;;
      t) AUDIO_LOW_THRESH="$OPTARG" ;;
      C) DEFAULT_COLOR="$OPTARG" ;;
      c) MUTED_COLOR="$OPTARG" ;;
      i) AUDIO_INTERVAL="$OPTARG" ;;
      h) printf \
"Usage: volume-pulseaudio [-l] [-F format] [-f format] [-p] [-a|-d] [-H symb] [-M symb]
        [-L symb] [-X symb] [-T thresh] [-t thresh] [-C color] [-c color] [-i inter] [-h]
Options:
-F, -f\tOutput format (-F long format, -f short format) to use, amonst:
\t0\t symb vol [index:name]\t (default long)
\t1\t symb vol [name]
\t2\t symb vol [index]\t (default short)
\t3\t symb vol
-p\tOmit the percent sign (%%) in volume
-a\tUse ALSA name if possible
-d\tUse device description instead of name if possible
-l\tPrint label
-H\tSymbol to use when audio level is high. Default: '$AUDIO_HIGH_SYMBOL'
-M\tSymbol to use when audio level is medium. Default: '$AUDIO_MED_SYMBOL'
-L\tSymbol to use when audio level is low. Default: '$AUDIO_LOW_SYMBOL'
-X\tSymbol to use when audio is muted. Default: '$AUDIO_MUTED_SYMBOL'
-T\tThreshold for medium audio level. Default: $AUDIO_MED_THRESH
-t\tThreshold for low audio level. Default: $AUDIO_LOW_THRESH
-C\tColor for non-muted audio. Default: $DEFAULT_COLOR
-c\tColor for muted audio. Default: $MUTED_COLOR
-i\tInterval size of volume increase/decrease. Default: $AUDIO_INTERVAL
-h\tShow this help text
" && exit 0;;
    esac
done

function move_sinks_to_new_default {
  DEFAULT_SINK=$1
  pacmd list-sink-inputs | grep index: | grep -o '[0-9]\+' | while read -r SINK
  do
    pacmd move-sink-input "$SINK" "$DEFAULT_SINK"
  done
}

function set_default_playback_device_next {
  inc=${1:-1}
  num_devices=$(pacmd list-sinks | grep -c index:)
  sink_arr=($(pacmd list-sinks | grep index: | grep -o '[0-9]\+'))
  default_sink_index=$(pacmd list-sinks | awk '/index:/ {if ( $1 == "*" ) print $3}')
  default_sink_index=$(( (default_sink_index + num_devices + inc) % num_devices ))
  default_sink=${sink_arr[$default_sink_index]}
  pacmd set-default-sink "$default_sink"
  move_sinks_to_new_default "$default_sink"
}

case "$BLOCK_BUTTON" in
    1) set_default_playback_device_next ;;
    2) amixer -q -D pulse sset Master toggle ;;
    3) set_default_playback_device_next -1 ;;
    4) amixer -q -D pulse sset Master "${AUDIO_INTERVAL}%+" ;;
    5) amixer -q -D pulse sset Master "${AUDIO_INTERVAL}%-" ;;
esac

function print_format {
  PERCENT="%"
  [[ $USE_PERCENT == 0 ]] && PERCENT=""
  case "$1" in
      1) echo "$VOL$PERCENT [$NAME]" ;;
      2) echo "$VOL$PERCENT [$INDEX]";;
      3) echo "$VOL$PERCENT" ;;
      *) echo "$VOL$PERCENT [$INDEX:$NAME]" ;;
  esac
}

function print_block {
  DEFAULT_SINK=$(pacmd stat | gawk  'BEGIN { FS=": " }; /Default sink name/ {print $2}')

  for name in INDEX NAME VOL MUTED ALSA_NAME DESCRIPTION; do
    read -r "$name"
  done < <(pacmd list-sinks | gawk "$AWK_PA_FILTER")

  if [[ $USE_ALSA_NAME == 1 ]] ; then
    NAME=${ALSA_NAME:-$NAME}
  elif [[ $USE_DESCRIPTION == 1 ]] ; then
    NAME=${DESCRIPTION:-$NAME}
  fi

  print_format "$LONG_FORMAT"
  print_format "$SHORT_FORMAT"
}

function print_label {
  DEFAULT_SINK=$(pacmd stat | gawk  'BEGIN { FS=": " }; /Default sink name/ {print $2}')

  for name in INDEX NAME VOL MUTED ALSA_NAME DESCRIPTION; do
    read -r $name
  done < <(pacmd list-sinks | gawk "$AWK_PA_FILTER")

  if [[ $MUTED =~ "no" ]] ; then
    SYMBOL=$AUDIO_HIGH_SYMBOL
    [[ $VOL -le $AUDIO_MED_THRESH ]] && SYMBOL=$AUDIO_MED_SYMBOL
    [[ $VOL -le $AUDIO_LOW_THRESH ]] && SYMBOL=$AUDIO_LOW_SYMBOL
    COLOR=$DEFAULT_COLOR
  else
    SYMBOL=$AUDIO_MUTED_SYMBOL
    COLOR=$MUTED_COLOR
  fi

  echo "$SYMBOL"
  echo "$SYMBOL"
  echo "$COLOR"
}

if [[ $LABEL_ONLY == 1 ]] ; then
  print_label
else
  print_block
fi
