#!/usr/bin/env zsh
# vim:set ft=zsh sw=2 sts=2 ts=2 et:

# see: https://wiki.archlinux.org/index.php/XDG_Base_Directory
# Home clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

if [ -z "$XDG_GREETER_DATA_DIR" ]; then
  # No duplicates in path arrays
  typeset -gU cdpath fpath mailpath PATH path
  # Source default profile if not done by system config
  grep -qc 'source /etc/profile' /etc/zsh/zprofile || \
    emulate sh -c 'source /etc/profile'
  path=(               \
    "$XDG_DATA_HOME/cargo/bin"  \
    "$HOME/.local/bin" \
    "$HOME/.yarn/bin"  \
    "$path[@]"         \
  )
  export PATH
else
  # Fallback for bash
  PATH="$XDG_DATA_HOME/cargo/bin:$HOME/.local/bin:$HOME/.yarn/bin:$PATH"
  export PATH=$(echo "$PATH" | \
    awk -v RS=':' -v ORS=":" '!a[$1]++{if (NR > 1) printf ORS; printf $a[$1]}')
fi

# Shortcut to dotfiles path is $DOTFILES
export DOTFILES="$XDG_CONFIG_HOME/dotfiles"

# Time format
export TIME="\t%e real,\t%U user,\t%S sys"

# Default Programs
export TERMINAL="alacritty"
export BROWSER="brave"
export READER="zathura"

# Default editor (will set zsh binds to vi mode)
if [ -n $(command -v nvim) ]; then
  export VIMCONFIG="$HOME/.config/nvim"
  export VIMDATA="$HOME/.local/share/nvim"
  export EDITOR='nvim'
  export VISUAL="nvim"
else
  export EDITOR='vi'
  export VISUAL="vi"
fi

# Pagers
# less: do not pollute home
export LESSHISTFILE="-"
export PAGER="less"
export MANPAGER="sh -c 'col -bx | bat -l man -p'"
export BAT_PAGER="less -RF"

# xmonad dirs
export XMONAD_CONFIG_DIR="$XDG_CONFIG_HOME/xmonad"
export XMONAD_CACHE_DIR="$XDG_CACHE_HOME/xmonad"
export XMONAD_DATA_DIR="$XDG_DATA_HOME/xmonad"

# kvm default connection
export VIRSH_DEFAULT_CONNECT_URI='qemu:///system'

# tmux config
export TMUX_CONF="$XDG_CONFIG_HOME/tmux/tmux.conf"
export TMUX_TMPDIR="$XDG_RUNTIME_DIR"

# autosuggetions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=10"
export ZSH_AUTOSUGGEST_USE_ASYNC=1

# ANSIBLE cfg
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"

# npm
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/config"

# GOLANG
export GOPATH="$XDG_DATA_HOME/go"

# Rust
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"

# FNM
export FNM_DIR="$XDG_DATA_HOME/fnm"

# Do not set SSH_AUTH_SOCKET on remote connection
if [[ -z "$SSH_CONNECTION" ]]; then
  export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR}/gnupg/S.gpg-agent.ssh"
fi

# x11
export ERRFILE="$XDG_CACHE_HOME/X11/xsession-errors"
