#
# zshenv is sourced on interactive login/non-login
#

export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# ensure compinit is started by prezto
skip_global_compinit=1
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
